# This is a configuration file that checks all the file for certain conditions before commiting

# Removing additional new lines at the end of each file
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks: 
    -   id: end-of-file-fixer
