# This file was created multiple commands for testing.

Dir := $(shell pwd)
Code_dir := $(subst tests/CodeInterpretation,projectCICD/AESClone,$(Dir))
Code_name := main.py

# Running the main code
run_main_py:
	@echo "\n"
	@echo "***	running the main.py ......	***\n"
	@ cd $(Code_dir); \
	python3.9 $(Code_name)
	@echo $(new_line)
	@echo "***	the code has successfully run .......	***\n"


Test_module:
	@echo $(new_line)
